apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: 487468996124.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:latest
          ports:
          - containerPort: 8080
      
